### ISSUE TITLE
Support horizontal animation width 0 to auto

### ISSUE THREAD

**Issue by Lamerchun** [smastrom/vue-collapsed#17]
Would it be possible to support width transition?

**Comment by smastrom** [comment]
Hi @Lamerchun, someone [already requested](https://github.com/smastrom/vue-collapsed/issues/12) this feature a while ago. in short, I'm not planning on adding it to vue-collapsed. 

Let me add another couple of lines to that, maybe they'll make things clear for others. Updating properties like width/height should be avoided as they cause a reflow, which is the event that triggers a DOM layout recalculation (very expensive). 

```css
.Collapse {
  height: 400px;
}
```
DOM layout must be recalculated by the browser...


```js
document.querySelector('.Collapse').clientHeight // 400
```
...in order to update the `clientHeight` after setting it via CSS.

Instead some properties like CSS transforms (translate, scale, etc) don't cause a reflow so they're great for transitions performance.

In the case of a FAQ accordion or a vertical nested menu, there isn't much we can do with transforms and transitioning the height is only way to go.

That's the reason why this package exist. I basically needed a solution for myself and decided to share it as I think it is the right thing to do.

But, most important of all, I don't encourage people using it for components like sliding navigation menus or expandable views. In that case, using CSS transforms is the way to go.

Hope it helps. Cheers!

**Comment by smastrom** [comment]
Hi @Lamerchun, someone [already requested](https://github.com/smastrom/vue-collapsed/issues/12) this feature a while ago. in short, I'm not planning on adding it to vue-collapsed. 

Let me add another couple of lines to that, maybe they'll make things clear for others. Updating properties like width/height should be avoided as they cause a reflow, which is the event that triggers a DOM layout recalculation (very expensive). 

```css
.Collapse {
  height: 400px;
}
```
DOM layout must be recalculated by the browser...


```js
document.querySelector('.Collapse').clientHeight // 400
```
...in order to update the `clientHeight` after setting it via CSS.

Instead some properties like CSS transforms (translate, scale, etc) don't cause a reflow so they're great for transitions performance.

In the case of a FAQ accordion or a vertical nested menu, there isn't much we can do with transforms and transitioning the height is the only way to go.

That's the reason why this package exist. I basically needed a solution for myself and decided to share it as I think it is the right thing to do.

But, most important of all, I don't encourage people using it for components like sliding navigation menus or expandable views. In that case, using CSS transforms is the way to go.

Hope it helps. Cheers!
